"""clients, market data and portfolio schema

Revision ID: ffa2e5f8a2d8
Revises: e1949c9f9b20
Create Date: 2026-09-21 00:58:23.236163+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ffa2e5f8a2d8'
down_revision: str | None = 'e1949c9f9b20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('tax_id', sa.String(length=14), nullable=False),
    sa.Column('tax_id_kind', sa.String(length=4), nullable=False),
    sa.Column('suitability', sa.String(length=20), nullable=False),
    sa.Column('suitability_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_index(op.f('ix_clients_tax_id'), 'clients', ['tax_id'], unique=True)
    op.create_table('instruments',
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('mic', sa.String(length=8), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('cfi', sa.String(length=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments'))
    )
    op.create_index(op.f('ix_instruments_asset_class'), 'instruments', ['asset_class'], unique=False)
    op.create_index(op.f('ix_instruments_isin'), 'instruments', ['isin'], unique=True)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('portfolios',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('base_currency', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    op.create_index(op.f('ix_portfolios_client_id'), 'portfolios', ['client_id'], unique=False)
    op.create_index(op.f('ix_portfolios_status'), 'portfolios', ['status'], unique=False)
    op.create_table('portfolio_targets',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('weight_bps', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_targets_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_targets'))
    )
    op.create_index(op.f('ix_portfolio_targets_portfolio_id'), 'portfolio_targets', ['portfolio_id'], unique=False)
    op.create_table('portfolio_transactions',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('notes', sa.String(length=280), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_transactions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_transactions'))
    )
    op.create_index('ix_portfolio_transactions_portfolio_id_trade_date', 'portfolio_transactions', ['portfolio_id', 'trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portfolio_transactions_portfolio_id_trade_date', table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_targets_portfolio_id'), table_name='portfolio_targets')
    op.drop_table('portfolio_targets')
    op.drop_index(op.f('ix_portfolios_status'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_client_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_isin'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_asset_class'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_clients_tax_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
